test yml gitactions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,14 +48,24 @@ jobs:
           exit 1
         fi
 
-    - name: Download and install ChromeDriver
+    - name: Obtain Chrome version
       run: |
         CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
+        if [ -z "$CHROME_VERSION" ]; then
+          echo "Failed to obtain Chrome version."
+          exit 1
+        fi
+
+    - name: Obtain ChromeDriver version
+      run: |
         CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
         if [ -z "$CHROMEDRIVER_VERSION" ]; then
           echo "Failed to fetch ChromeDriver version."
           exit 1
         fi
+
+    - name: Download and install ChromeDriver
+      run: |
         if ! wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; then
           echo "Failed to download ChromeDriver."
           exit 1
