test yml gitactions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,8 +50,19 @@ jobs:
           exit 1
         fi
 
+    - name: Download and install ChromeDriver
+      run: |
+        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Failed to fetch ChromeDriver version."
+          exit 1
+        fi
+        wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
+        unzip -qq /tmp/chromedriver_linux64.zip -d /tmp
+        chmod +x /tmp/chromedriver
+        sudo mv /tmp/chromedriver /usr/local/bin/
+
     - name: Run Robot Framework tests
       env:
-        SELENIUM_BROWSER: chrome
-        SELENIUM_BROWSER_EXECUTABLE_PATH: /usr/bin/google-chrome
+        CHROME_BIN: /usr/bin/google-chrome
       run: robot --variable BROWSER:headlesschrome tests/
