test yml gitactions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,7 +32,10 @@ jobs:
 
     - name: Add Google Chrome repository key
       run: |
-        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
+        if ! wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -; then
+          echo "Failed to add Google Chrome repository key"
+          exit 1
+        fi
 
     - name: Add Google Chrome repository
       run: |
@@ -40,16 +43,32 @@ jobs:
 
     - name: Install Google Chrome
       run: |
-        apt-get update && apt-get install -y google-chrome-stable
+        if ! apt-get update && apt-get install -y google-chrome-stable; then
+          echo "Failed to install Google Chrome"
+          exit 1
+        fi
 
     - name: Download and install ChromeDriver
       run: |
         CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
         CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
-        wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
-        unzip -qq /tmp/chromedriver_linux64.zip -d /tmp
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Failed to fetch ChromeDriver version."
+          exit 1
+        fi
+        if ! wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; then
+          echo "Failed to download ChromeDriver."
+          exit 1
+        fi
+        if ! unzip -qq /tmp/chromedriver_linux64.zip -d /tmp; then
+          echo "Failed to unzip ChromeDriver."
+          exit 1
+        fi
         chmod +x /tmp/chromedriver
-        mv /tmp/chromedriver /usr/local/bin/
+        if ! mv /tmp/chromedriver /usr/local/bin/; then
+          echo "Failed to move ChromeDriver."
+          exit 1
+        fi
 
     - name: Run Robot Framework tests
       run: robot --variable BROWSER:headlesschrome tests/
