test yml gitactions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,33 +42,28 @@ jobs:
       run: |
         apt-get update && apt-get install -y google-chrome-stable
 
-    - name: Obtain Chrome version (corrected)
+    - name: Obtain Chrome version
       run: |
-          CHROME_VERSION=$(google-chrome-stable --version 2>&1 | awk '{print $3}' | cut -d '.' -f 1)
-          if [ $? -eq 0 ]; then
-            echo "Chrome version obtained: $CHROME_VERSION"
-          else
-            echo "Failed to obtain Chrome version. See output above for details."
-            exit 1
-          fi
+        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
+        if [ -z "$CHROME_VERSION" ]; then
+          echo "Failed to obtain Chrome version."
+          exit 1
+        fi
+        echo "Chrome version: $CHROME_VERSION"
 
     - name: Download and install ChromeDriver
       run: |
         CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
-        CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
-        wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
+        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Failed to obtain ChromeDriver version."
+          exit 1
+        fi
+        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
+        wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
         unzip -qq /tmp/chromedriver_linux64.zip -d /tmp
         chmod +x /tmp/chromedriver
-        mv /tmp/chromedriver /usr/local/bin/
-
-    - name: Add ChromeDriver to PATH
-      run: echo "export PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV
+        sudo mv /tmp/chromedriver /usr/local/bin/
 
     - name: Run Robot Framework tests
-      run: robot --variable BROWSER:headlesschrome --argument "--headless" --argument "--disable-gpu" --argument "--no-sandbox" tests/
-
-    - name: Upload test results
-      uses: actions/upload-artifact@v2
-      with:
-        name: test-results
-        path: reports/output.xml
+      run: robot --variable BROWSER:headlesschrome tests/
